# Generated by Django 5.0.6 on 2024-07-09 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_por_noche', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='masaje',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='precio_noche',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='sauna',
        ),
        migrations.AddField(
            model_name='reserva',
            name='servicios_extra',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.hotel'),
        ),
    ]
